{
 "title": "Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Throughtput and Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughtput",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec{topic=\"raw.measurements\"})",
     "legendFormat": "Kafka"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kappa",
     "rawSql": "select\n    avg(timestampdiff(second, ingestion_timestamp, aggregation_timestamp)) as `Avg Overall Latency`,\n    avg(timestampdiff(second, ingestion_timestamp, enrichment_timestamp)) as `Avg Enrichment Latency`,\n    avg(timestampdiff(second, enrichment_timestamp, routing_timestamp)) as `Avg Routing Latency`,\n    avg(timestampdiff(second, routing_timestamp, scoring_timestamp)) as `Avg Scoring Latency`,\n    avg(timestampdiff(second, scoring_timestamp, union_timestamp)) as `Avg Union Latency`,\n    avg(timestampdiff(second, union_timestamp, aggregation_timestamp)) as `Avg Aggregation Latency`\nfrom paimon.delta.gdnews2_scores"
    }
   ]
  },
  { "title": "Hardware Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"jobmanager\"}",
     "legendFormat": "Job Manager"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-taskmanager1-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-taskmanager2-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-taskmanager3-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-taskmanager4-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"kafka-1\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"kafka-2\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"kafka-3\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"zookeeper-1\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"zookeeper-2\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"zookeeper-3\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-doris-fe-1\"}",
     "legendFormat": "Doris Frontend"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-doris-be-1-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-doris-be-2-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"tesis-kappa-doris-be-3-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"minio\"}",
     "legendFormat": "Object Storage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"jobmanager\"}",
     "legendFormat": "Job Manager"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-taskmanager1-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-taskmanager2-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-taskmanager3-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-taskmanager4-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"kafka-1\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"kafka-2\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"kafka-3\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"zookeeper-1\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"zookeeper-2\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"zookeeper-3\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-doris-fe-1\"}",
     "legendFormat": "Doris Frontend"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-doris-be-1-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-doris-be-2-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"tesis-kappa-doris-be-3-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_memory_usage_bytes{name=\"minio\"}",
     "legendFormat": "Object Storage"
    }
   ]
  },
  {
   "title": "Network Transmition",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"jobmanager\"}",
     "legendFormat": "Job Manager"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-taskmanager1-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-taskmanager2-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-taskmanager3-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-taskmanager4-1\"}",
     "legendFormat": "Task Manager"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"kafka-1\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"kafka-2\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"kafka-3\"}",
     "legendFormat": "Kafka"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"zookeeper-1\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"zookeeper-2\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"zookeeper-3\"}",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-doris-fe-1\"}",
     "legendFormat": "Doris Frontend"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-doris-be-1-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-doris-be-2-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"tesis-kappa-doris-be-3-1\"}",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "dockerstats_network_transmitted_bytes{name=\"minio\"}",
     "legendFormat": "Object Storage"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_log_log_totalsize)",
     "legendFormat": "Kafka"
    },
    {
     "expr": "doris_be_disks_local_used_capacity",
     "legendFormat": "Doris Backend"
    },
    {
     "expr": "minio_cluster_usage_total_bytes",
     "legendFormat": "Object Storage"
    }
   ]
  }
 ]
}