version: '3.9'
services:
  jobmanager:
    image: flink:1.20.0
    container_name: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH='hadoop classpath'
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.bind-host: 0.0.0.0
        rest.bind-address: 0.0.0.0
        state.backend: hashmap
        state.backend.incremental: true
        state.checkpoints.dir: file:///opt/flink/checkpoints
        state.savepoints.dir: file:///opt/flink/savepoints
        sql-gateway.enabled: true
        sql-gateway.endpoint.rest.port: 8083
        sql-gateway.endpoint.rest.address: 0.0.0.0
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9249
        metrics.reporter.prom.host: 0.0.0.0
        metrics.reporters: prom
        metrics.reporter.prom.interval: 60 SECONDS
        jobmanager.memory.process.size: 5g
        jobmanager.memory.heap.size: 3g
        jobmanager.memory.off-heap.size: 1g
        jobmanager.memory.jvm-metaspace.size: 512m
        jobmanager.memory.jvm-overhead.min: 256m
        jobmanager.memory.jvm-overhead.max: 1g
    ports:
      - "10200:8081"
      - "10210:8083"
    command: jobmanager
    volumes:
      - ./container/jars/flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar
      - ./container/jars/flink-doris-connector-1.20-24.1.0.jar:/opt/flink/lib/flink-doris-connector-1.20-24.1.0.jar
      - ./container/jars/flink-connector-jdbc-3.2.0-1.19.jar:/opt/flink/lib/flink-connector-jdbc-3.2.0-1.19.jar
      - ./container/jars/postgresql-42.7.5.jar:/opt/flink/lib/postgresql-42.7.5.jar
      - ./container/jars/flink-metrics-prometheus-1.20.0.jar:/opt/flink/lib/flink-metrics-prometheus-1.20.0.jar
      - ./container/jars/paimon-flink-1.20-1.1.jar:/opt/flink/lib/paimon-flink-1.20-1.1.jar
      - ./container/jars/flink-s3-fs-hadoop-1.20.0.jar:/opt/flink/lib/flink-s3-fs-hadoop-1.20.0.jar
      - ./container/jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./container/jars/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar
      - ./container/jars/paimon-s3-1.1.jar:/opt/flink/lib/paimon-s3-1.1.jar
      - ./container/config/sql-client-defaults.yaml:/opt/flink/conf/sql-client-defaults.yaml
      - ./container/jobs:/opt/flink/bin/jobs
    networks:
      delta:
        ipv4_address: 172.20.3.2

  taskmanager1:
    image: flink:1.20.0
    deploy: &tm-deploy
      resources:
        limits:
          cpus: '5.0'
          memory: 18G
        reservations:
          cpus: '4.0'
          memory: 16G
    environment: &tm-env
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH='hadoop classpath'
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_PATH_STYLE_ACCESS=true
      - |
        FLINK_PROPERTIES=
        taskmanager.numberOfTaskSlots: 10
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9249
        metrics.reporter.prom.host: 0.0.0.0
        metrics.reporters: prom
        metrics.reporter.prom.interval: 60 SECONDS
        taskmanager.memory.jvm-overhead.min: 256m
        taskmanager.memory.jvm-overhead.max: 3g
        taskmanager.memory.process.size: 16g
        taskmanager.memory.task.heap.size: 8g
        taskmanager.memory.managed.size: 4g
        taskmanager.memory.network.min: 1g
        taskmanager.memory.network.max: 1g
        taskmanager.memory.framework.heap.size: 1g
        state.backend: hashmap
        state.backend.incremental: true
        state.checkpoints.dir: file:///opt/flink/checkpoints
        state.savepoints.dir: file:///opt/flink/savepoints
    depends_on:
      - jobmanager
    command: taskmanager
    volumes: &tm-volumes
      - ./container/jars/flink-sql-connector-kafka-3.3.0-1.20.jar:/opt/flink/lib/flink-sql-connector-kafka-3.3.0-1.20.jar
      - ./container/jars/flink-doris-connector-1.20-24.1.0.jar:/opt/flink/lib/flink-doris-connector-1.20-24.1.0.jar
      - ./container/jars/flink-connector-jdbc-3.2.0-1.19.jar:/opt/flink/lib/flink-connector-jdbc-3.2.0-1.19.jar
      - ./container/jars/postgresql-42.7.5.jar:/opt/flink/lib/postgresql-42.7.5.jar
      - ./container/jars/flink-metrics-prometheus-1.20.0.jar:/opt/flink/lib/flink-metrics-prometheus-1.20.0.jar
      - ./container/jars/paimon-flink-1.20-1.1.jar:/opt/flink/lib/paimon-flink-1.20-1.1.jar
      - ./container/jars/flink-s3-fs-hadoop-1.20.0.jar:/opt/flink/lib/flink-s3-fs-hadoop-1.20.0.jar
      - ./container/jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./container/jars/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar
      - ./container/jars/paimon-s3-1.1.jar:/opt/flink/lib/paimon-s3-1.1.jar
    networks:
      - delta

  taskmanager2:
    image: flink:1.20.0
    environment: *tm-env
    depends_on:
      - jobmanager
    command: taskmanager
    volumes: *tm-volumes
    networks:
      - delta

  taskmanager3:
    image: flink:1.20.0
    environment: *tm-env
    depends_on:
      - jobmanager
    command: taskmanager
    volumes: *tm-volumes
    networks:
      - delta

  taskmanager4:
    image: flink:1.20.0
    environment: *tm-env
    depends_on:
      - jobmanager
    command: taskmanager
    volumes: *tm-volumes
    networks:
      - delta